# These are supported funding model platforms

github: LeanBitLab
patreon: # [username]
open_collective: # [username]
ko_fi: # [username]
tidelift: # [platform-name/package-name]
community_bridge: # [cloud-transport-project-name]
liberapay: # [username]
issuehunt: # [username]
otechie: # [username]
custom: # [https://url.to.your.custom.funding.page]
