title: "[Offline AI] "
labels: ["offline-ai"]
body:
  - type: markdown
    attributes:
      value: |
        Discuss features, models, and performance of the On-Device Offline AI.
  - type: input
    id: model
    attributes:
      label: Model Name
      description: Which model are you using? (e.g., Xenova/flan-t5-small)
      placeholder: Xenova/flan-t5-small
    validations:
      required: true
  - type: input
    id: device_specs
    attributes:
      label: Device Specs (RAM/CPU)
      description: Important for performance debugging.
      placeholder: 8GB RAM, Snapdragon 8 Gen 2
    validations:
      required: true
  - type: textarea
    id: feedback
    attributes:
      label: Feedback / Issue
      description: Describe your experience or request.
      placeholder: The grammar correction is slow...
    validations:
      required: true
