title: "[Q&A] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Please search existing discussions and issues before asking.
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of LeanType are you using?
      placeholder: v3.7.2
    validations:
      required: true
